version: '3.0'

services:
   db:
     image: mysql
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: automarket
       MYSQL_USER: dockermysqluser
       MYSQL_PASSWORD: _Password001
     volumes:
       - dbdata:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
     restart: always

   automarketapi:
     depends_on:
       - db
     image: automarketapi:v1
     build:
       context: .
     ports:
       - "8080:5000"

volumes:
    dbdata: