-- MySQL Script generated by MySQL Workbench
-- Sat Oct 15 22:14:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema automarket
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema automarket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `automarket` DEFAULT CHARACTER SET utf8 ;
USE `automarket` ;

-- -----------------------------------------------------
-- Table `automarket`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `automarket`.`product` ;

CREATE TABLE IF NOT EXISTS `automarket`.`product` (
  `ProductId` CHAR(36) NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Description` VARCHAR(255) NULL,
  `ImagePath` VARCHAR(255) NULL,
  PRIMARY KEY (`ProductId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `automarket`.`product_variant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `automarket`.`product_variant` ;

CREATE TABLE IF NOT EXISTS `automarket`.`product_variant` (
  `ProductVariantId` CHAR(36) NOT NULL,
  `Info` VARCHAR(45) NULL,
  `Price` DECIMAL NULL,
  `ProductId` CHAR(36) NOT NULL,
  PRIMARY KEY (`ProductVariantId`),
  INDEX `fk_product_variant_product_idx` (`ProductId` ASC) VISIBLE,
  CONSTRAINT `fk_product_variant_product`
    FOREIGN KEY (`ProductId`)
    REFERENCES `automarket`.`product` (`ProductId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `automarket`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `automarket`.`user` ;

CREATE TABLE IF NOT EXISTS `automarket`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;